title:            Causation, Mechanism & Difference Makers
tagline:          philosophy of science
description:      conference website
canonical: http://philcog.github.io

# Owner/author information
owner:
  name:           CMDMC
  avatar:         avatar.png
  disqus:         philcog        # Plug in your disqus shortname!
  location:       "Copenhagen, Denmark"
  email:          gsj868@hum.ku.dk
#  bio:            "Aesthete & Athlete"
#  twitter:        twnsndco
#  github:         coletownsend
#  instagram:      ctrunsthis
#  dribbble:       coletownsend



# Authors 
#authors:
#  author1:
#    name: Philcog
#    display_name: philcog
#    gravatar: c66919cb194f9fkdfkdsjfk696c1da0c47354a6a
#    email: philcogscie@gmail.com
#    web: http://company.com
#    twitter: company
#    github: one
#  author2:
#    name: Author Two
#    display_name: Two
#    gravatar: 12e480a364a5c14214f99b4dfe9a11d5
#    email: two@company.com
#    web: http://company.com
#    twitter: company
#    github: two

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Links to include in top navigation
# For external links add external: true
links:
#  - title: About
#    url: /about
  - title: Program
    url: /program
    external: false
  - title: Abstracts
    url: /abstracts
    external: false
  - title: Practical
    url: /practical
    external: false

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Copenhagen
future:      true
highlighter: pygments
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

sass:
    style: :compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
